<?php
/**
 * Builds the client-side search index used by the search box in both skins.
 *
 * Run manually whenever archive/data/threads/*.json changes:
 *
 *   php public/archive/build-search-index.php
 *
 * Reads the archive JSON (archive/data/site.json + archive/data/threads/*.json) and writes
 * archive/assets/shared/search-index.js: a plain JS file (not .json, so archive/.htaccess's
 * deny rule doesn't block it) that assigns window.VM_SEARCH for archive/assets/shared/search.js
 * to search against. Not part of the request-handling code path; not reachable over HTTP either way.
 *
 * window.VM_SEARCH shape:
 *   {
 *     perPage: 10,                                   // posts per thread page, for building #t=..&p=.. links
 *     threads: { "<tid>": [title, forumName, fid] },
 *     posts: [ [tid, pid, page, author, dateIso, text], ... ],  // text is plain (HTML stripped, sig excluded)
 *     users: [ "Name", ... ],                         // distinct authors, sorted case-insensitively
 *   }
 */

const ARCHIVE_DIR = __DIR__;

function load_json(string $relative): ?array
{
    $path = ARCHIVE_DIR . '/data/' . $relative;
    if (!is_file($path)) {
        return null;
    }
    $decoded = json_decode((string) file_get_contents($path), true);
    return is_array($decoded) ? $decoded : null;
}

/** Strip HTML, decode entities, collapse whitespace: post HTML -> plain searchable text. */
function plain_text(string $html): string
{
    $text = strip_tags($html);
    $text = html_entity_decode($text, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
    $text = preg_replace('/\s+/u', ' ', $text) ?? $text;
    return trim($text);
}

$site = load_json('site.json');
if ($site === null) {
    fwrite(STDERR, "search index: archive/data/site.json not found, nothing to build.\n");
    exit(1);
}
$perPage = max(1, (int) $site['per_page']);

$threads = [];
$posts = [];
$usersSeen = []; // lowercase name => display name

$files = glob(ARCHIVE_DIR . '/data/threads/*.json') ?: [];
sort($files, SORT_NATURAL);

foreach ($files as $file) {
    $thread = json_decode((string) file_get_contents($file), true);
    if (!is_array($thread) || empty($thread['posts'])) {
        continue;
    }
    $tid = (int) $thread['tid'];
    $crumbs = $thread['crumbs'] ?? [];
    $lastCrumb = end($crumbs) ?: null;
    $forumName = $lastCrumb['name'] ?? '';
    $fid = (int) ($lastCrumb['fid'] ?? 0);

    $threads[$tid] = [$thread['title'] ?? '', $forumName, $fid];

    foreach (array_values($thread['posts']) as $i => $p) {
        $author = (string) ($p['author'] ?? '');
        if ($author !== '') {
            $key = mb_strtolower($author);
            $usersSeen[$key] ??= $author;
        }
        $text = plain_text((string) ($p['html'] ?? ''));
        if ($text === '' && ($p['title'] ?? '') === '') {
            continue; // nothing worth indexing (e.g. an empty/removed post)
        }
        $page = intdiv($i, $perPage) + 1;
        $posts[] = [
            $tid,
            (int) $p['pid'],
            $page,
            $author,
            $p['date'] ?? null,
            $text,
        ];
    }
}

$users = array_values($usersSeen);
usort($users, fn ($a, $b) => strcasecmp($a, $b));

$index = [
    'perPage' => $perPage,
    'threads' => $threads,
    'posts' => $posts,
    'users' => $users,
];

$json = json_encode($index, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
if ($json === false) {
    fwrite(STDERR, "search index: json_encode failed: " . json_last_error_msg() . "\n");
    exit(1);
}

$out = "// Generated by build-search-index.php — do not edit by hand.\n"
     . "window.VM_SEARCH = " . $json . ";\n";

$outPath = ARCHIVE_DIR . '/assets/shared/search-index.js';
file_put_contents($outPath, $out);

fwrite(STDOUT, sprintf(
    "search index: %d threads, %d posts, %d users -> %s (%s)\n",
    count($threads),
    count($posts),
    count($users),
    $outPath,
    format_bytes(strlen($out))
));

function format_bytes(int $bytes): string
{
    if ($bytes < 1024) {
        return $bytes . ' B';
    }
    $kb = $bytes / 1024;
    if ($kb < 1024) {
        return round($kb, 1) . ' KB';
    }
    return round($kb / 1024, 2) . ' MB';
}
